# generated by distribution
set.seed(12321)
rnorm(10,0,1)
rbinom(6,size=c(1,2),prob=0.5)
runif(50,min=0,max=10)

x<-matrix(rnorm((1000*100),896,174),nrow=1000)
means<-apply(x,MARGIN = 1,FUN=mean)
sdevs<-apply(x,MARGIN = 1,FUN=sd)
median<-apply(x,MARGIN = 1,FUN=median)
r<-apply(x,MARGIN = 1,FUN=range)
range<-apply(r,MARGIN = 2,FUN=diff)
par(mfrow=c(2,2))
hist(means,main='mean')
hist(sdevs,main='sdevs')
hist(median,main='median')
hist(range,main='range')

# excercise
dis<-function(x,y,po=0.5){
  d<-sqrt((x-po)^2+(y-po)^2)
  return (d)
}
mypi<-function(n){
x<-runif(n,min=0,max=2*po)
y<-runif(n,min=0,max=2*po)
df<-cbind(x,y)
d<-dis(df[,1],df[,2])
p<-sum(d<po)/n
pai<-4*p
dev<-abs(pi-pai)
re<-cbind(pai,dev)
names(re)<-c('estimate','deviation')
return (re)}
n<-seq(1000,100000,1000)
mplot<-sapply(n, function(n) mypi(n))
par(mfrow=c(2,1))
plot(n,mplot[1,],pch=19,type = 'o',xlab = 'times',ylab = 'estimate')
lines(n,rep(pi,length(n)),col='red')
plot(n,mplot[2,],pch=19,type = 'o',xlab = 'times',ylab = 'deviation')
lines(n,rep(0,length(n)),col='red')

mydtbt<-function(y){
sm<-mean(y)
s2m<-mean(y,trim=0.2)
sme<-median(y)
e<-c(sm,s2m,sme)
names(e)<-c('mean','20% trimmed mean','median')
return (e)}
m<-1000
n<-100
mu<-2
sd<-3
x<-matrix(rnorm((m*n),mu,sd),ncol=n)
est<-apply(x,MARGIN = 2,FUN = mydtbt)
bias<-abs(mu-est)
rowMeans(est)
rowMeans(bias)

myclt<-function(x){
  mx<-apply(x,MARGIN = 2,FUN = mean)
  hist(mx,probability=T)
  ms<-mean(mx)
  sds<-sd(mx)
  y<-rnorm(10000,ms,sds)
  lines(density(y),col='red')
  re<-cbind(ms,sds)
  names(re)<-c('mean','sd')
  return (re)
}
m<-1000
n<-100
mu<-2
sd<-3
x<-matrix(rnorm((m*n),mu,sd),ncol=n)
myclt(x)
x<-matrix(runif((m*n),mu,sd),ncol=n)
myclt(x)
